### ISSUE TITLE
Review Module 10 - Laravel PHP Framework

### ISSUE THREAD

**Issue by millidavids** [millidavids/Laravel-Test#1]

**Comment by millidavids** [comment]
@bkuhl

**Comment by bkuhl** [comment]
This looks really good.  Just 2 things I either can't find or still need to be done:
- Create 1 facade (_You've used them, but there isn't a custom one_)
- Building out a crud controller (you don't need to do both)

**Comment by millidavids** [comment]
Cool. I guess I misread about the Facade. I'll get right on it.

**Comment by millidavids** [comment]
@bkuhl Just added in the full crud controller. e1935d86b750c2cbfb465d2bebac406b801d849f

**Comment by millidavids** [comment]
@bkuhl Just added the custom facade. 302f0886946fed5fe9f8e05ee5e87c2d9a793392

**Comment by bkuhl** [comment]
Did you get a chance to add the form validation?

**Comment by millidavids** [comment]
Added in form request validation for the store company action. 
50a6f8d82d1cb831a1dbad642a2d1ad77e786060

cannot figure out why gitignore won't ignore the .vagrant directory, oh well

**Comment by jlaswell** [comment]
Update `/.vagrant` to `.vagrant` in the `.gitignore` file.

**Comment by millidavids** [comment]
I guess I fat fingered that backslash in there :/

**Comment by bkuhl** [comment]
:+1: Nice
